fixtures:
  symlinks:
    symfony: "#{source_dir}"
  repositories:
    stdlib:   "git://github.com/puppetlabs/puppetlabs-stdlib"
    git:      "git://github.com/puppetlabs/puppetlabs-git"
    composer: "git://github.com/tPl0ch/puppet-composer"
