name         'gowili-symfony'
version      '0.0.1'
license      'MIT License'
summary      'A Puppet module to manage Symfony applications'
description  'Execute Symfony Console commands, run composer scripts, etc.'
project_page 'https://github.com/gowili/puppet-symfony'
dependency   'tPl0ch/composer', '>= 1.2.1'
